### PR TITLE
Ensure that the MPS builds with "clang -Werror -Wcomma -std=c89"

### LINKED ISSUE #47: MPS does not build with -Wcomma
This is a problem because Xcode 12.3 seems to turn this on automatically (see #46), and so users may encounter this when they upgrade Xcode even if they didn't ask for it specifically.
```
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.28)
$ clang -Werror -Wcomma -std=c89 -c mps.c
In file included from mps.c:53:
./bt.c:1008:26: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (fromBit = fromBase, toBit = toBase;
                         ^
./bt.c:1008:8: note: cast expression to void to silence warning
  for (fromBit = fromBase, toBit = toBase;
       ^~~~~~~~~~~~~~~~~~
       (void)(           )
In file included from mps.c:58:
./sac.c:26:13: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = 0, cb = fb->_blocks; j < fb->_count; ++j) {
            ^
./sac.c:26:8: note: cast expression to void to silence warning
  for (j = 0, cb = fb->_blocks; j < fb->_count; ++j) {
       ^~~~~
       (void)( )
./sac.c:52:32: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = sac->middleIndex + 1, i = 0; j < sac->classesCount; ++j, i += 2) {
                               ^
./sac.c:52:8: note: cast expression to void to silence warning
  for (j = sac->middleIndex + 1, i = 0; j < sac->classesCount; ++j, i += 2) {
       ^~~~~~~~~~~~~~~~~~~~~~~~
       (void)(                 )
./sac.c:70:28: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = sac->middleIndex, i = 1; j > 0; --j, i += 2) {
                           ^
./sac.c:70:8: note: cast expression to void to silence warning
  for (j = sac->middleIndex, i = 1; j > 0; --j, i += 2) {
       ^~~~~~~~~~~~~~~~~~~~
       (void)(             )
./sac.c:160:27: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = middleIndex + 1, i = 0; j < classesCount; ++j, i += 2) {
                          ^
./sac.c:160:8: note: cast expression to void to silence warning
  for (j = middleIndex + 1, i = 0; j < classesCount; ++j, i += 2) {
       ^~~~~~~~~~~~~~~~~~~
       (void)(            )
./sac.c:170:23: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = middleIndex, i = 1; j > 0; --j, i += 2) {
                      ^
./sac.c:170:8: note: cast expression to void to silence warning
  for (j = middleIndex, i = 1; j > 0; --j, i += 2) {
       ^~~~~~~~~~~~~~~
       (void)(        )
./sac.c:271:13: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = 0, fl = esac->_freelists[i]._blocks;
            ^
./sac.c:271:8: note: cast expression to void to silence warning
  for (j = 0, fl = esac->_freelists[i]._blocks;
       ^~~~~
       (void)( )
./sac.c:307:13: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = 0, fl = esac->_freelists[i]._blocks;
            ^
./sac.c:307:8: note: cast expression to void to silence warning
  for (j = 0, fl = esac->_freelists[i]._blocks;
       ^~~~~
       (void)( )
./sac.c:372:32: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = sac->middleIndex + 1, i = 0;
                               ^
./sac.c:372:8: note: cast expression to void to silence warning
  for (j = sac->middleIndex + 1, i = 0;
       ^~~~~~~~~~~~~~~~~~~~~~~~
       (void)(                 )
./sac.c:380:28: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = sac->middleIndex, i = 1; j > 0; --j, i += 2) {
                           ^
./sac.c:380:8: note: cast expression to void to silence warning
  for (j = sac->middleIndex, i = 1; j > 0; --j, i += 2) {
       ^~~~~~~~~~~~~~~~~~~~
       (void)(             )
In file included from mps.c:60:
./poolmrg.c:777:14: error: possible misuse of comma operator here [-Werror,-Wcomma]
    for(i = 0, link = (Link)SegBase(MustBeA(Seg, linkSeg)),
             ^
./poolmrg.c:777:9: note: cast expression to void to silence warning
    for(i = 0, link = (Link)SegBase(MustBeA(Seg, linkSeg)),
        ^~~~~
        (void)( )
./poolmrg.c:777:59: error: possible misuse of comma operator here [-Werror,-Wcomma]
    for(i = 0, link = (Link)SegBase(MustBeA(Seg, linkSeg)),
                                                          ^
./poolmrg.c:777:16: note: cast expression to void to silence warning
    for(i = 0, link = (Link)SegBase(MustBeA(Seg, linkSeg)),
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               (void)(                                    )
In file included from mps.c:78:
./nailboard.c:373:13: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = i, jbase = ibase;;) {
            ^
./nailboard.c:373:8: note: cast expression to void to silence warning
  for (j = i, jbase = ibase;;) {
       ^~~~~
       (void)( )
./nailboard.c:388:13: error: possible misuse of comma operator here [-Werror,-Wcomma]
  for (j = i, jlimit = ilimit;;) {
            ^
./nailboard.c:388:8: note: cast expression to void to silence warning
  for (j = i, jlimit = ilimit;;) {
       ^~~~~
       (void)( )
14 errors generated.
```

### PR DESCRIPTION
**Pull request by gareth-rees**
The -Wcomma option appears to be turned on automatically by Xcode 12.3, so it's a good idea for the MPS to build with the option, to avoid unpleasant surprises when people update their Xcode.

The simplest way to suppress the warning is to cast the left hand side of the comma operator to void.

Fixes #47.

### CODE REVIEW

**Review by rptb1 — COMMENTED** [review]
This issue seems to occur exclusively where we have created `for` loops with more than one variable.  I'm wondering whether we shouldn't just ban those, because they are now hard to read.  They do, however, express something about the loop invariants that would be lost if we moved the variable updates out of the `for`. Opinions?

**Comment by gareth-rees** [comment]
I considered moving some of the assignments out of the loops, but I decided against it because (i) it would make it harder to review; and (ii) the use of multiple variables in a loop expresses an intention (usually that the variables iterate together according to an invariant) that would be lost if we moved one of the variables out of the loop.

I am not averse to trying to refactor these loops, but I think it should be done in a separate issue and pull request. The problem being solved here is "MPS does not build in Xcode 12.3" and I think it is a better engineering approach to focus on solving the critical problem first, and the less critical problem (the code becomes somewhat harder to follow) in a separate step.

In most cases it looks to me as though a second loop variable has been introduced as a kind of hand-optimization, for example in amcsshe.c we have:
```
char *p = (char*)exactRoots[r];
for(i = 0; i < bogusRootsCOUNT; (void)(++i), ++p)
  bogusRoots[i] = (mps_addr_t)p;
```
where the increment of `p` on each loop is a kind of strength reduction optimization. But compilers are perfectly capable of doing that optimization themselves these days (when it is worth it), so we can write:
```
for(i = 0; i < bogusRootsCOUNT; ++i)
  bogusRoots[i] = (mps_addr_t)(p + i);
```
without any loss of performance (even if performance mattered here, which it almost certainly doesn't).

**Comment by gareth-rees** [comment]
@rptb1 See the updated pull request — I've added a commit that refactors all the loops to improve maintainability, as requested.

**Comment by rptb1** [comment]
> In most cases it looks to me as though a second loop variable has been introduced as a kind of hand-optimization, for example in amcsshe.c we have ...

For future reference, you can select a line number range, "copy permalink", from code and paste that in, like this

https://github.com/Ravenbrook/mps/blob/d13e2855bfeceaa14b942e7b9e90af7a15de04ad/code/amcsshe.c#L195-L196

And then it can be clicked through.

File: code/misc.h [hunk 1]
```diff
@@ -245,6 +245,13 @@ typedef const struct SrcIdStruct {
 #define ERRNO_RESTORE END; errno = _saved_errno; END
 
 
+/* Iterate over two expressions in parallel, avoiding warnings from
+ * clang -Wcomma -std=c89.
```
Comment (rptb1) [inline code/misc.h:249]:
```suggestion
 * clang -Wcomma -std=c89, while clearly expressing intention.  See
 * <https://github.com/Ravenbrook/mps/pull/48#issuecomment-757458796>.
```

**Review by rptb1 — CHANGES_REQUESTED** [review]
This is a good general cleanup.
